CREATE TABLE address (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    uf VARCHAR(255) NOT NULL,
    zip_code VARCHAR(255) NOT NULL
);